require("dotenv").config();

const {
  PORT,

  SALESFORCE_CLIENT_ID,
  SALESFORCE_CLIENT_SECRET,
  SALESFORCE_CALLBACK_URL,

  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_S3_BUCKET,
  AWS_ENDPOINT,

  SESSION_SECRET,
} = process.env;

module.exports = {
  PORT,

  SALESFORCE_CLIENT_ID,
  SALESFORCE_CLIENT_SECRET,
  SALESFORCE_CALLBACK_URL,

  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_S3_BUCKET,
  AWS_ENDPOINT,

  SESSION_SECRET,
};
